use_visualization: true
use_painted_image: true
is_local_runtime: true

capturer:
  show_loss_framerate: false
  show_loss_framerate_interval: 500
  reconnect_wait_interval: 100
  # hikcamera or local_video
  source: "hikcamera"
  hikcamera:
    # int
    timeout_ms: 500
    # float
    exposure_us: 2000.0
    # float
    framerate: 60
    # float
    gain: 16.9807

    invert_image: false
    software_sync: false
    trigger_mode: false
    fixed_framerate: true
  local_video:
    # 替换为你具体的路径
    location: "/workspaces/alliance/test_videos/solve_pnp_v2.mp4"
    # double 帧率
    frame_rate: 60
    # bool 是否循环播放
    loop_play: true
    # bool 是否允许跳帧以满足实时性
    allow_skipping: false

identifier:
  binarization_threshold: 0.5

  # openvino infer
  model_location: "yolov5.xml"
  infer_device: "AUTO"
  use_roi_segment: false
  use_corner_correction: false
  roi_rows: 640
  roi_cols: 640
  input_rows: 640
  input_cols: 640
  min_confidence: 0.5
  score_threshold: 0.7
  nms_threshold: 0.3

tracker:
  # blue or red
  enemy_color: red

pose_estimator:
  camera_matrix: [1.722231837421459e+03, 0, 7.013056440882832e+02, 0, 1.724876404292754e+03,5.645821718351237e+02 , 0, 0, 1]
  distort_coeff: [-0.064232403853946, -0.087667493884102, 0,0, 0.792381808294582]

  transforms:
    - parent: "imu_link"
      child: "pitch_link"
      t: [0., 0., 0.]
      q: [1., 0., 0., 0.]
    - parent: "pitch_link"
      child: "muzzle_link"
      t: [0., 0., 0.]
      q: [1., 0., 0., 0.]
    - parent: "pitch_link"
      child: "camera_link"
      t: [0., 0., 0.]
      q: [1., 0., 0., 0.]

visualization:
  framerate: 60
  monitor_host: "127.0.0.1"
  monitor_port: "5000"
  stream_type: "RTP_JEPG"
